"""delete unique into field CommentModel.task_id unique

Revision ID: 0071f67f212f
Revises: 981f619b165e
Create Date: 2026-05-03 14:26:59.931004

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0071f67f212f"
down_revision: Union[str, Sequence[str], None] = "981f619b165e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("comments_task_id_key"), "comments", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("comments_task_id_key"),
        "comments",
        ["task_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
