"""change status filed in TaskModel

Revision ID: 0ae24ae53698
Revises: a425c57dcdfa
Create Date: 2026-04-02 10:17:09.401227

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0ae24ae53698"
down_revision: Union[str, Sequence[str], None] = "a425c57dcdfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "status",
        existing_type=postgresql.ENUM(
            "todo", "in_progress", "done", name="status_enum"
        ),
        type_=sa.Enum("open", "in_work", "done", name="status_enum", native_enum=False),
        existing_nullable=False,
    )
    op.alter_column("tasks", "author_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "author_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column(
        "tasks",
        "status",
        existing_type=sa.Enum(
            "open", "in_work", "done", name="status_enum", native_enum=False
        ),
        type_=postgresql.ENUM("todo", "in_progress", "done", name="status_enum"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
