"""delete nullable from title and description in MeetingModel

Revision ID: 222dcefe1d9d
Revises: 43cc73758235
Create Date: 2026-05-18 09:08:33.926102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '222dcefe1d9d'
down_revision: Union[str, Sequence[str], None] = '43cc73758235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'title',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('meetings', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('meetings', 'title',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
