"""rename Task to TaskModel

Revision ID: 2eec2513b38e
Revises: 4bd67b4130c7
Create Date: 2026-03-30 19:56:42.797536

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2eec2513b38e"
down_revision: Union[str, Sequence[str], None] = "4bd67b4130c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
