"""Add order by to relate TaskModel.comments

Revision ID: 376ddba90a7f
Revises: 73e2f0159270
Create Date: 2026-05-04 11:34:18.429132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '376ddba90a7f'
down_revision: Union[str, Sequence[str], None] = '73e2f0159270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
