"""add forign_keys to relationship users in TeamModel

Revision ID: 3a398c691325
Revises: d2cb904ae316
Create Date: 2026-04-17 14:51:36.164958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a398c691325'
down_revision: Union[str, Sequence[str], None] = 'd2cb904ae316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
