"""Add canceled field to MeetingModel

Revision ID: 41776d26d3ea
Revises: 117ac2be1a31
Create Date: 2026-05-14 11:21:28.995379

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "41776d26d3ea"
down_revision: Union[str, Sequence[str], None] = "117ac2be1a31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("meetings", sa.Column("canceled", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meetings", "canceled")
    # ### end Alembic commands ###
