"""Add ordering to meeting and tasks relate in UserModel

Revision ID: 43cc73758235
Revises: ca6b8c4464fc
Create Date: 2026-05-15 12:42:37.927370

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "43cc73758235"
down_revision: Union[str, Sequence[str], None] = "ca6b8c4464fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
