"""Add user meetings table and links in relate

Revision ID: 60fef95dbcfd
Revises: 7133c9980fb4
Create Date: 2026-05-12 13:23:17.706848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '60fef95dbcfd'
down_revision: Union[str, Sequence[str], None] = '7133c9980fb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_meetings',
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'meeting_id')
    )
    op.create_index(op.f('ix_users_meetings_meeting_id'), 'users_meetings', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_users_meetings_user_id'), 'users_meetings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_meetings_user_id'), table_name='users_meetings')
    op.drop_index(op.f('ix_users_meetings_meeting_id'), table_name='users_meetings')
    op.drop_table('users_meetings')
    # ### end Alembic commands ###
