"""Remove TeamRoleType from TeamModel and add to UserModel

Revision ID: 7317e766c6c1
Revises: adec8ca0fa56
Create Date: 2026-04-17 14:25:14.682999

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7317e766c6c1"
down_revision: Union[str, Sequence[str], None] = "adec8ca0fa56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teams", "team_role")
    op.add_column(
        "users",
        sa.Column(
            "team_role",
            sa.Enum("manager", "employee", name="team_role_enum", native_enum=False),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "team_role")
    op.add_column(
        "teams",
        sa.Column("team_role", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
