"""Add title and dewscription to Meeting Model

Revision ID: 9717a0d6063d
Revises: 60fef95dbcfd
Create Date: 2026-05-13 15:03:36.665634

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9717a0d6063d"
down_revision: Union[str, Sequence[str], None] = "60fef95dbcfd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("meetings", sa.Column("title", sa.String(length=50), nullable=True))
    op.add_column(
        "meetings", sa.Column("description", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meetings", "description")
    op.drop_column("meetings", "title")
    # ### end Alembic commands ###
