"""delete one to one relationship in CommentModel

Revision ID: 981f619b165e
Revises: bfb67f8e8321
Create Date: 2026-05-03 14:24:30.740387

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "981f619b165e"
down_revision: Union[str, Sequence[str], None] = "bfb67f8e8321"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
