"""Add TeamModel

Revision ID: adec8ca0fa56
Revises: 0ae24ae53698
Create Date: 2026-04-17 10:30:20.563781

"""

import fastapi_users_db_sqlalchemy
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "adec8ca0fa56"
down_revision: Union[str, Sequence[str], None] = "0ae24ae53698"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "team_role",
            sa.Enum(name="team_role_enum", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "admin_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("users", sa.Column("team_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "users", "teams", ["team_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "team_id")
    op.drop_table("teams")
    # ### end Alembic commands ###
