"""delete one to one relationship in TaskModel.comments

Revision ID: bfb67f8e8321
Revises: fde3569d7525
Create Date: 2026-05-03 14:21:55.173250

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "bfb67f8e8321"
down_revision: Union[str, Sequence[str], None] = "fde3569d7525"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
