"""Add foreign_keys to tasks field in UserModel

Revision ID: ca6b8c4464fc
Revises: db1c1d1d4c21
Create Date: 2026-05-15 10:30:50.767897

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ca6b8c4464fc"
down_revision: Union[str, Sequence[str], None] = "db1c1d1d4c21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
