"""Adding tasks relation to UserModel

Revision ID: db1c1d1d4c21
Revises: 0d2dd6964482
Create Date: 2026-05-15 10:23:06.311914

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "db1c1d1d4c21"
down_revision: Union[str, Sequence[str], None] = "0d2dd6964482"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
