"""add field username to CommentModel

Revision ID: e7bb520dfbb0
Revises: 0071f67f212f
Create Date: 2026-05-03 14:45:46.343906

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e7bb520dfbb0"
down_revision: Union[str, Sequence[str], None] = "0071f67f212f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("username", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("comments", "username")
    # ### end Alembic commands ###
